language: cpp
dist: bionic
os: linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    # AMOR API
    #- libboost-thread-dev

    # AMOR API, YARP and KDL
    - libeigen3-dev

    # OpenRAVE
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-python-dev
    - libboost-thread-dev
    - libboost-iostreams-dev
    - libqt4-dev
    - qt4-dev-tools
    - libxml2-dev
    - libode-dev
    - libsoqt4-dev
    - libcoin80-dev

    # ROBOTICSLAB
    - libopencv-dev
    - libpcl-dev
    - libspnav-dev
    - libxwiimote-dev

before_install:
  #-- Register SSH deploy key for AMOR API private repository
  - source "$TRAVIS_BUILD_DIR/scripts/travis/configure-ssh.sh"

before_script:
  # Reduce build log verbosity
  - export CFLAGS="-w"
  - export CXXFLAGS="-w"

  - mkdir build && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install-system" -DNON_INTERACTIVE_BUILD=ON -DYCM_GIT_GITHUB_BASE_ADDRESS="git@github.com:"

script:
  - make install

after_success:
  - make uninstall
