language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

  #-- Configure Git (needed by YCM)
  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

  #-- Register SSH deploy key for AMOR API private repository
  #-- https://gist.github.com/lukewpatterson/4242707#gistcomment-2382443
  #-- http://anil.recoil.org/2013/10/06/travis-secure-ssh-integration.html
  - mkdir -p ~/.ssh
  - echo $DEPLOY_KEY_AMOR_API | base64 --decode | openssl aes-256-cbc -K $encrypted_7783b7b455a9_key -iv $encrypted_7783b7b455a9_iv -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo "Host *" >> ~/.ssh/config
  - echo "    StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "    CheckHostIP no" >> ~/.ssh/config
  - echo "    PasswordAuthentication no" >> ~/.ssh/config
  - echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

install:
  #-- Install AMOR API deps (already covered in following sections)
  #- sudo apt-get install libeigen3-dev libboost-thread-dev

  #-- Install YARP and KDL deps
  - sudo apt-get install libeigen3-dev # Needed for creating YARP lib_math

  #-- Install OpenRAVE deps
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libqt4-dev qt4-dev-tools libxml2-dev libode-dev # libfcl-dev not on Trusty used in this travis
  - sudo apt-get install libsoqt4-dev libcoin80-dev

  #-- Install OpenCV
  - sudo apt-get install libopencv-dev

  #-- Install PCL
  ##- sudo add-apt-repository --yes ppa:v-launchpad-jochen-sprickerhof-de/pcl
  ##- sudo apt-get -qq update
  ##- sudo apt-get install libpcl-all libpcl-all-dev

  #-- Install ROBOTICSLAB deps
  - sudo apt-get install libspnav-dev libxwiimote-dev

before_script:
  - mkdir build && cd "$_"
  - cmake .. -DYCM_GIT_GITHUB_BASE_ADDRESS="git@github.com:"

script:
  - make

after_success:
  - sudo make install
  - sudo make uninstall
